import dotenv from "dotenv";
dotenv.config();

import mongoose from "mongoose";
import { connectDB, closeDB } from "../config/db.js";
import User from "../models/User.js";
import OrganizerProfile from "../models/OrganizerProfile.js";
import Event from "../models/Event.js";
import Registration from "../models/Registration.js";
import Category from "../models/Category.js";
import Announcement from "../models/Announcement.js";
import Banner from "../models/Banner.js";
import { logger } from "../utils/logger.js";

export const seedData = async (standalone = true) => {
  logger.info("==========================================");
  logger.info("Starting Ignite Enginow Database Seed...");
  logger.info("==========================================");

  if (standalone) {
    await connectDB();
  }

  // Clear existing collections
  await Promise.all([
    User.deleteMany({}),
    OrganizerProfile.deleteMany({}),
    Event.deleteMany({}),
    Registration.deleteMany({}),
    Category.deleteMany({}),
    Announcement.deleteMany({}),
    Banner.deleteMany({}),
  ]);

  logger.info("Cleared existing database records.");

  // 1. Seed Categories matching platform taxonomy
  const categories = await Category.insertMany([
    { name: "Hackathon", description: "Multi-day building competitions & prize challenges", active: true, displayOrder: 1 },
    { name: "Workshop", description: "Hands-on practical sessions guided by domain experts", active: true, displayOrder: 2 },
    { name: "Webinar", description: "Interactive live masterclasses and industry panels", active: true, displayOrder: 3 },
    { name: "Bootcamp", description: "Intensive multi-week skill acceleration cohorts", active: true, displayOrder: 4 },
    { name: "Conference", description: "Keynotes, showcases, and networking summits", active: true, displayOrder: 5 },
    { name: "Meetup", description: "Local and regional community gatherings", active: true, displayOrder: 6 },
    { name: "AI / ML", description: "Artificial intelligence, deep learning, & LLMs", active: true, displayOrder: 7 },
    { name: "Web Development", description: "Frontend, backend, APIs, and modern frameworks", active: true, displayOrder: 8 },
    { name: "Cloud & DevOps", description: "Infrastructure, Docker, Kubernetes, & CI/CD", active: true, displayOrder: 9 },
    { name: "Cyber Security", description: "Application security, ethical hacking, and cryptography", active: true, displayOrder: 10 },
    { name: "Robotics", description: "Hardware, ROS, IoT, and embedded automation", active: true, displayOrder: 11 },
    { name: "College Festival", description: "Inter-collegiate technical and cultural symposiums", active: true, displayOrder: 12 },
    { name: "Networking", description: "Professional mixers, investor lounges, and mentorship circles", active: true, displayOrder: 13 },
  ]);
  logger.info(`Seeded ${categories.length} categories.`);

  // 2. Seed Users
  const student = await User.create({
    name: "Aarav Sharma",
    email: "aarav.sharma@campus.edu",
    role: "student",
    isRoleSelected: true,
    accountStatus: "active",
    headline: "CS & AI Undergraduate · Hackathon Enthusiast",
    college: "Indian Institute of Technology (IIT)",
    bio: "Passionate about machine learning, distributed systems, and competitive coding.",
    skills: ["Python", "PyTorch", "React", "TypeScript", "FastAPI"],
    github: "github.com/aaravsharma",
    linkedin: "linkedin.com/in/aaravsharma",
  });

  const student2 = await User.create({
    name: "Priya Sundaram",
    email: "priya.s@tech.ac.in",
    role: "student",
    isRoleSelected: true,
    accountStatus: "active",
    headline: "Full-Stack Engineer & Open Source Contributor",
    college: "BITS Pilani",
    bio: "Web3 & Cloud architect.",
    skills: ["Go", "Node.js", "Kubernetes", "Next.js"],
  });

  const organizerUser = await User.create({
    name: "DevSphere Foundation",
    email: "events@devsphere.org",
    role: "organizer",
    isRoleSelected: true,
    accountStatus: "active",
    headline: "Global Technical Community & Hackathon Organizers",
    college: "DevSphere Labs",
    bio: "Empowering 50,000+ engineers worldwide through open hackathons and technical summits.",
  });

  const organizerUser2 = await User.create({
    name: "OpenKernel Community",
    email: "team@openkernel.org",
    role: "organizer",
    isRoleSelected: true,
    accountStatus: "active",
    headline: "Open Source Systems & Developer Community",
    college: "OpenKernel Org",
    bio: "Democratizing systems engineering and low-level software.",
  });

  const adminUser = await User.create({
    name: "Sarah Chen (Admin)",
    email: "sarah.chen@enginow.io",
    role: "admin",
    isRoleSelected: true,
    accountStatus: "active",
    headline: "Platform Operations & Governance Lead",
  });

  logger.info("Seeded core persona users.");

  // 3. Seed Organizer Profiles
  await OrganizerProfile.create({
    user: organizerUser._id,
    organizationName: "DevSphere Foundation",
    organizationType: "Global Community Foundation",
    description: "Empowering 50,000+ engineers worldwide through open hackathons, bootcamps, and developer workshops.",
    website: "https://devsphere.org",
    contactEmail: "events@devsphere.org",
    contactPhone: "+91 98765 43210",
    verificationStatus: "APPROVED",
    submittedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    reviewedAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000),
    reviewedBy: adminUser._id,
    eventsCount: 6,
  });

  await OrganizerProfile.create({
    user: organizerUser2._id,
    organizationName: "OpenKernel Community",
    organizationType: "Open Source Foundation",
    description: "Building developer education pathways in distributed systems, OS kernels, and cloud tooling.",
    website: "https://openkernel.org",
    contactEmail: "team@openkernel.org",
    verificationStatus: "APPROVED",
    submittedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
    reviewedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
    reviewedBy: adminUser._id,
    eventsCount: 6,
  });

  logger.info("Seeded approved OrganizerProfiles.");

  // 4. Seed Full Events Catalog (12 Approved + 1 Pending Review)
  const eventsData = [
    {
      title: "Quantum Hack 2026",
      slug: "quantum-hack-2026",
      tagline: "India's Premier 48-Hour Hybrid Hackathon on Edge AI & Distributed Systems",
      about: "A flagship hybrid hackathon bringing together 1,200+ builders across quantum computing, applied ML, and edge devices. Ship a working prototype in 48 hours, get mentored by leading engineers, and pitch to a jury of investors and researchers.",
      category: "Hackathon",
      mode: "Hybrid",
      location: "Bengaluru + Online",
      city: "Bengaluru",
      college: "IIT Bengaluru",
      eventDate: new Date("2026-10-15T09:00:00Z"),
      dateLabel: "Oct 15 – 17, 2026",
      durationLabel: "48 hours",
      registrationDeadline: new Date("2026-10-12T23:59:59Z"),
      price: "Free",
      registrationFee: "Free",
      prize: "₹10,00,000 Prize Pool",
      capacity: 800,
      seats: 800,
      registeredCount: 612,
      coverImage: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&auto=format&fit=crop&q=80",
      status: "APPROVED",
      organizer: organizerUser._id,
      organizerName: "DevSphere Foundation",
      approvedBy: adminUser._id,
      approvedAt: new Date(),
      publishedAt: new Date(),
      isFeatured: true,
      registrationsOpen: true,
      tags: ["Quantum", "AI", "ML", "Hackathon", "Prize"],
      speakers: [
        { name: "Dr. Priya Nair", role: "Quantum Research Lead, IBM" },
        { name: "Arun Krishnan", role: "Principal Engineer, Google DeepMind" },
      ],
      agenda: [
        { time: "Day 1 · 09:00", title: "Opening keynote", description: "Framing the problem space with industry leaders." },
        { time: "Day 1 · 11:00", title: "Team formation & ideation", description: "Structured matchmaking and problem selection." },
        { time: "Day 2 · 10:00", title: "Mentor office hours", description: "1:1 sessions with domain mentors." },
        { time: "Day 3 · 14:00", title: "Final demos & judging", description: "Live demo in front of a live jury." },
      ],
      perks: ["Swag kit", "Certificate of participation", "Mentor access", "Recruiter shortlist"],
      faqs: [
        { q: "Can I participate solo?", a: "Yes, solo participation is allowed but teams of 2–4 are preferred." },
        { q: "Is accommodation provided?", a: "We provide venue access. Travel and stay are at participant's expense." },
        { q: "What tech stack can I use?", a: "Any language or framework — this is an open hackathon." },
      ],
    },
    {
      title: "Designing Systems That Scale",
      slug: "designing-systems-that-scale",
      tagline: "A hands-on workshop on distributed systems, from first principles to production.",
      about: "Learn the mental models used by senior engineers to design services that scale — queues, caches, sharding, and failure handling. Live coding, real diagrams, and a take-home exercise.",
      category: "Workshop",
      mode: "Online",
      location: "Live on Enginow",
      city: "Online",
      eventDate: new Date("2026-07-22T14:00:00Z"),
      dateLabel: "Jul 22, 2026",
      durationLabel: "3 hours",
      registrationDeadline: new Date("2026-07-20T23:59:59Z"),
      price: "₹499",
      registrationFee: "₹499",
      capacity: 300,
      seats: 300,
      registeredCount: 214,
      coverImage: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1200&auto=format&fit=crop&q=80",
      status: "APPROVED",
      organizer: organizerUser2._id,
      organizerName: "OpenKernel Community",
      approvedBy: adminUser._id,
      approvedAt: new Date(),
      publishedAt: new Date(),
      isFeatured: true,
      registrationsOpen: true,
      tags: ["Distributed Systems", "Backend", "Architecture", "Paid"],
      speakers: [{ name: "Aarav Mehta", role: "Staff Engineer, Fintech" }],
      agenda: [
        { time: "00:00", title: "Fundamentals of scale", description: "Latency vs throughput and system SLOs." },
        { time: "00:45", title: "Data plane patterns", description: "Caches, queues, and consistency choices." },
        { time: "01:45", title: "Live design session", description: "Design a real-world system with the room." },
      ],
      perks: ["Recording access", "Design worksheets", "Certificate"],
    },
    {
      title: "Building AI Products Users Love",
      slug: "ai-product-webinar",
      tagline: "A 60-minute webinar with product leaders shipping AI at scale.",
      about: "What separates AI features that stick from ones that don't? A candid conversation on evals, latency, trust, and product craft with leaders who have shipped LLM features to 50M+ users.",
      category: "Webinar",
      mode: "Online",
      location: "Live on Enginow",
      city: "Online",
      eventDate: new Date("2026-07-05T16:00:00Z"),
      dateLabel: "Jul 5, 2026",
      durationLabel: "60 min",
      registrationDeadline: new Date("2026-07-04T23:59:59Z"),
      price: "Free",
      registrationFee: "Free",
      capacity: 2000,
      seats: 2000,
      registeredCount: 1587,
      coverImage: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1200&auto=format&fit=crop&q=80",
      status: "APPROVED",
      organizer: organizerUser._id,
      organizerName: "DevSphere Foundation",
      approvedBy: adminUser._id,
      approvedAt: new Date(),
      publishedAt: new Date(),
      isFeatured: true,
      registrationsOpen: true,
      tags: ["AI", "Product Management", "Free", "Webinar"],
      speakers: [
        { name: "Isha Rao", role: "Head of Product, AI Platform" },
        { name: "Vikram Sethi", role: "VP Engineering, OpenAI" },
      ],
      agenda: [
        { time: "00:00", title: "Opening + framing", description: "Where AI actually earns its keep." },
        { time: "00:15", title: "Panel discussion", description: "Product leaders on their hardest calls." },
        { time: "00:45", title: "Live Q&A", description: "Audience questions." },
      ],
      perks: ["Live Q&A", "Slides & recording"],
    },
    {
      title: "Modern Frontend Bootcamp",
      slug: "frontend-bootcamp-2026",
      tagline: "Four weekends. Ship a production-grade React + TypeScript app.",
      about: "A cohort-based bootcamp taught by working engineers. Weekly live sessions, code reviews, and a capstone project reviewed by mentors from Stripe and Notion.",
      category: "Bootcamp",
      mode: "Online",
      location: "Cohort-based",
      city: "Online",
      eventDate: new Date("2026-09-05T10:00:00Z"),
      dateLabel: "Sep 5 – 28, 2026",
      durationLabel: "4 weeks",
      registrationDeadline: new Date("2026-09-01T23:59:59Z"),
      price: "₹4,999",
      registrationFee: "₹4,999",
      capacity: 120,
      seats: 120,
      registeredCount: 46,
      coverImage: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&auto=format&fit=crop&q=80",
      status: "APPROVED",
      organizer: organizerUser2._id,
      organizerName: "OpenKernel Community",
      approvedBy: adminUser._id,
      approvedAt: new Date(),
      publishedAt: new Date(),
      isFeatured: false,
      registrationsOpen: true,
      tags: ["React", "TypeScript", "Frontend", "Bootcamp", "Paid"],
      speakers: [
        { name: "Sania Mirza", role: "Senior Frontend Engineer, Stripe" },
        { name: "Rohan Gupta", role: "Tech Lead, Notion" },
      ],
      agenda: [
        { time: "Week 1", title: "Architecture", description: "Routing, state, and data patterns." },
        { time: "Week 2", title: "UI craft", description: "Design systems, motion, and a11y." },
        { time: "Week 3", title: "Data & auth", description: "Query patterns and secure auth flows." },
        { time: "Week 4", title: "Ship the capstone", description: "Deploy and demo." },
      ],
      perks: ["Live cohort", "Mentor reviews", "Capstone certificate", "Alumni network"],
    },
    {
      title: "DevFest South 2026",
      slug: "devfest-south-2026",
      tagline: "The regional gathering for engineers, designers, and builders.",
      about: "A full-day conference with talks, workshops, and side quests. Meet founders, engineers, and the people building the next wave of technology in India.",
      category: "Conference",
      mode: "In-person",
      location: "HICC, Hyderabad",
      city: "Hyderabad",
      eventDate: new Date("2026-11-08T09:30:00Z"),
      dateLabel: "Nov 8, 2026",
      durationLabel: "1 day",
      registrationDeadline: new Date("2026-11-01T23:59:59Z"),
      price: "₹1,499",
      registrationFee: "₹1,499",
      capacity: 1200,
      seats: 1200,
      registeredCount: 803,
      coverImage: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&auto=format&fit=crop&q=80",
      status: "APPROVED",
      organizer: organizerUser._id,
      organizerName: "DevSphere Foundation",
      approvedBy: adminUser._id,
      approvedAt: new Date(),
      publishedAt: new Date(),
      isFeatured: true,
      registrationsOpen: true,
      tags: ["Conference", "Networking", "Paid", "In-person"],
      speakers: [
        { name: "Ananya Das", role: "Engineering Director, Flipkart" },
        { name: "Karan Mehta", role: "Founder, HealthAI" },
      ],
      agenda: [
        { time: "09:30", title: "Registration & coffee", description: "Pick up your badge." },
        { time: "10:15", title: "Keynote", description: "State of the ecosystem." },
        { time: "12:00", title: "Talks & workshops", description: "Parallel tracks." },
        { time: "18:00", title: "After hours", description: "Networking dinner." },
      ],
      perks: ["Full-day access", "Swag", "Recorded talks", "After-party"],
    },
    {
      title: "Engineers Meetup — Bengaluru",
      slug: "engineers-meetup-blr",
      tagline: "A curated monthly meetup for engineers building at frontier companies.",
      about: "An intimate, invite-only gathering with lightning talks and open conversations. High signal, low noise. Meet tech leads, staff architects, and fellow innovators.",
      category: "Meetup",
      mode: "In-person",
      location: "WeWork, Bengaluru",
      city: "Bengaluru",
      eventDate: new Date("2026-07-19T18:30:00Z"),
      dateLabel: "Jul 19, 2026",
      durationLabel: "3 hours",
      registrationDeadline: new Date("2026-07-18T23:59:59Z"),
      price: "Free",
      registrationFee: "Free",
      capacity: 120,
      seats: 120,
      registeredCount: 118,
      coverImage: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200&auto=format&fit=crop&q=80",
      status: "APPROVED",
      organizer: organizerUser2._id,
      organizerName: "OpenKernel Community",
      approvedBy: adminUser._id,
      approvedAt: new Date(),
      publishedAt: new Date(),
      isFeatured: false,
      registrationsOpen: true,
      tags: ["Networking", "Free", "In-person", "Bengaluru"],
      speakers: [],
      agenda: [
        { time: "18:30", title: "Doors", description: "Coffee and intros." },
        { time: "19:00", title: "Lightning talks", description: "Three 10-minute talks." },
        { time: "20:00", title: "Open discussion", description: "Roundtable conversation." },
      ],
      perks: ["Community access", "Curated attendee list"],
    },
    {
      title: "Autonomous Agents Summit",
      slug: "autonomous-agents-summit",
      tagline: "Architecture, Tool-Calling, and Safety in Large Language Model Agentic Systems",
      about: "A deep-dive technical conference exploring practical multi-agent coordination, memory architectures, evals, and production latency optimization.",
      category: "AI / ML",
      mode: "Online",
      location: "Virtual (Live Streamed)",
      city: "Online",
      eventDate: new Date("2026-11-05T14:00:00Z"),
      dateLabel: "Nov 5, 2026",
      durationLabel: "6 hours",
      registrationDeadline: new Date("2026-11-04T23:59:59Z"),
      price: "Free",
      registrationFee: "Free",
      capacity: 500,
      seats: 500,
      registeredCount: 110,
      coverImage: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=1200&auto=format&fit=crop&q=80",
      status: "APPROVED",
      organizer: organizerUser._id,
      organizerName: "DevSphere Foundation",
      approvedBy: adminUser._id,
      approvedAt: new Date(),
      publishedAt: new Date(),
      isFeatured: true,
      registrationsOpen: true,
      tags: ["AI Agents", "LLMs", "AI / ML", "Conference"],
      speakers: [
        { name: "Dr. Elena Rostova", role: "AI Research Director, QuantumFlow" },
        { name: "Marcus Thorne", role: "VP Engineering, Distributed Scale" },
      ],
      agenda: [
        { time: "14:00", title: "Agent Architectures in 2026", description: "ReAct, Tool-Calling, and Reflection Patterns." },
        { time: "16:00", title: "Safety and Guardrails", description: "Preventing hallucinations and sandbox breakouts." },
        { time: "18:00", title: "Open Agent Frameworks Showcase", description: "Live demos of next-gen autonomous systems." },
      ],
      perks: ["Certificates", "Speaker Q&A", "Source Code Repositories"],
    },
    {
      title: "Cloud Native & Kubernetes Summit 2026",
      slug: "cloud-native-k8s-summit",
      tagline: "Master eBPF, service meshes, GitOps, and platform engineering at scale.",
      about: "Join 1,000+ infrastructure architects and DevOps engineers to discuss real-world multi-cluster Kubernetes deployments, zero-trust network policies, and eBPF observability.",
      category: "Cloud & DevOps",
      mode: "In-person",
      location: "Sheraton Grand, Pune",
      city: "Pune",
      eventDate: new Date("2026-11-14T09:00:00Z"),
      dateLabel: "Nov 14, 2026",
      durationLabel: "1 day",
      registrationDeadline: new Date("2026-11-10T23:59:59Z"),
      price: "₹999",
      registrationFee: "₹999",
      capacity: 600,
      seats: 600,
      registeredCount: 340,
      coverImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=80",
      status: "APPROVED",
      organizer: organizerUser2._id,
      organizerName: "OpenKernel Community",
      approvedBy: adminUser._id,
      approvedAt: new Date(),
      publishedAt: new Date(),
      isFeatured: false,
      registrationsOpen: true,
      tags: ["Cloud", "Kubernetes", "DevOps", "Docker", "eBPF"],
      speakers: [
        { name: "Tanvi Patel", role: "Principal Cloud Architect, RedHat" },
        { name: "David Miller", role: "Core Maintainer, CNCF" },
      ],
      perks: ["Cloud Workshop Access", "Swag Bag", "Lunch & Networking"],
    },
    {
      title: "Autonomous Robotics Challenge 2026",
      slug: "robotics-challenge-2026",
      tagline: "Build autonomous rovers navigating dynamic obstacle courses using ROS 2.",
      about: "An adrenaline-fueled arena robotics challenge. Build and deploy perception algorithms, SLAM navigation, and real-time obstacle avoidance on physical quadrupeds and rovers.",
      category: "Robotics",
      mode: "In-person",
      location: "IIT Bombay Gymkhana Grounds, Mumbai",
      city: "Mumbai",
      eventDate: new Date("2026-12-02T10:00:00Z"),
      dateLabel: "Dec 2 – 4, 2026",
      durationLabel: "3 days",
      registrationDeadline: new Date("2026-11-25T23:59:59Z"),
      price: "Free",
      registrationFee: "Free",
      prize: "₹4,00,000 Prize Pool",
      capacity: 350,
      seats: 350,
      registeredCount: 220,
      coverImage: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=1200&auto=format&fit=crop&q=80",
      status: "APPROVED",
      organizer: organizerUser._id,
      organizerName: "DevSphere Foundation",
      approvedBy: adminUser._id,
      approvedAt: new Date(),
      publishedAt: new Date(),
      isFeatured: true,
      registrationsOpen: true,
      tags: ["Robotics", "ROS", "Hardware", "Automation", "IoT"],
      speakers: [
        { name: "Prof. S. Ranganathan", role: "Head of Robotics Lab, IITB" },
      ],
      perks: ["Hardware Toolkits", "Trophies & Bounties", "Industry Sponsorships"],
    },
    {
      title: "CyberStrike: Red Team vs Blue Team CTF",
      slug: "cyberstrike-ctf-2026",
      tagline: "24-hour Capture The Flag tournament tackling web exploits, reverse engineering, and binary analysis.",
      about: "Test your cybersecurity capabilities against real-world adversarial environments. Track challenges across Web Exploitation, Cryptography, Reverse Engineering, and Binary Exploitation.",
      category: "Cyber Security",
      mode: "Online",
      location: "Virtual CTF Platform",
      city: "Online",
      eventDate: new Date("2026-10-24T12:00:00Z"),
      dateLabel: "Oct 24 – 25, 2026",
      durationLabel: "24 hours",
      registrationDeadline: new Date("2026-10-22T23:59:59Z"),
      price: "Free",
      registrationFee: "Free",
      prize: "₹2,50,000 + Certifications",
      capacity: 1000,
      seats: 1000,
      registeredCount: 780,
      coverImage: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1200&auto=format&fit=crop&q=80",
      status: "APPROVED",
      organizer: organizerUser2._id,
      organizerName: "OpenKernel Community",
      approvedBy: adminUser._id,
      approvedAt: new Date(),
      publishedAt: new Date(),
      isFeatured: false,
      registrationsOpen: true,
      tags: ["Cyber Security", "CTF", "Ethical Hacking", "Cryptography"],
      speakers: [
        { name: "Alok Verma", role: "Security Researcher, ZeroDay Lab" },
      ],
      perks: ["Offensive Security Vouchers", "Exclusive Discord Badge", "Leaderboard Hall of Fame"],
    },
    {
      title: "Full-Stack NextGen DevCon 2026",
      slug: "fullstack-devcon-2026",
      tagline: "State of React Server Components, Next.js 16, GraphQL, and Edge Runtimes.",
      about: "Join 800+ full-stack engineers in New Delhi to discuss bleeding-edge UI architecture, server actions, distributed state synchronization, and low-latency databases.",
      category: "Web Development",
      mode: "Hybrid",
      location: "India Habitat Centre, New Delhi",
      city: "New Delhi",
      eventDate: new Date("2026-11-28T09:00:00Z"),
      dateLabel: "Nov 28, 2026",
      durationLabel: "1 day",
      registrationDeadline: new Date("2026-11-24T23:59:59Z"),
      price: "₹799",
      registrationFee: "₹799",
      capacity: 450,
      seats: 450,
      registeredCount: 290,
      coverImage: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1200&auto=format&fit=crop&q=80",
      status: "APPROVED",
      organizer: organizerUser._id,
      organizerName: "DevSphere Foundation",
      approvedBy: adminUser._id,
      approvedAt: new Date(),
      publishedAt: new Date(),
      isFeatured: false,
      registrationsOpen: true,
      tags: ["Web Development", "React", "Next.js", "Full-Stack", "JavaScript"],
      speakers: [
        { name: "Kunal Shah", role: "Staff Web Architect" },
        { name: "Meera Nair", role: "VP Frontend Platform" },
      ],
      perks: ["Talk Recordings", "Lunch & Swag", "Hands-on Code Labs"],
    },
    {
      title: "National Collegiate Tech Fest 'Ignite 26'",
      slug: "collegiate-tech-fest-ignite26",
      tagline: "The largest multi-discipline inter-collegiate festival with hackathons, gaming, and robot wars.",
      about: "Ignite 26 brings together 50+ universities and 4,000+ students for three action-packed days of robotics arenas, code golf, paper presentations, gaming tournaments, and technical project displays.",
      category: "College Festival",
      mode: "In-person",
      location: "IIT Madras Campus, Chennai",
      city: "Chennai",
      eventDate: new Date("2026-12-18T09:00:00Z"),
      dateLabel: "Dec 18 – 20, 2026",
      durationLabel: "3 days",
      registrationDeadline: new Date("2026-12-14T23:59:59Z"),
      price: "₹299",
      registrationFee: "₹299",
      prize: "₹7,50,000 Total Prizes",
      capacity: 2500,
      seats: 2500,
      registeredCount: 1420,
      coverImage: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=1200&auto=format&fit=crop&q=80",
      status: "APPROVED",
      organizer: organizerUser._id,
      organizerName: "DevSphere Foundation",
      approvedBy: adminUser._id,
      approvedAt: new Date(),
      publishedAt: new Date(),
      isFeatured: true,
      registrationsOpen: true,
      tags: ["College Festival", "Robotics", "Gaming", "Hackathon", "Campus"],
      speakers: [
        { name: "Dr. K. Sivan", role: "Former ISRO Chairman (Guest of Honor)" },
      ],
      perks: ["All-Access Pass", "College Trophy Points", "Certificate of Participation", "Concert Night"],
    },
    // 1 Pending Review Event for admin approval testing
    {
      title: "Zero-Knowledge Cryptography Bootcamp",
      slug: "zk-cryptography-bootcamp",
      tagline: "Master PLONK, zk-SNARKs and Circom circuits in 4 intensive sessions",
      about: "Comprehensive engineering bootcamp on zero-knowledge proofs for scalability, cross-chain state verification, and identity privacy.",
      category: "Bootcamp",
      mode: "Online",
      location: "Virtual Cohort",
      city: "Online",
      eventDate: new Date("2026-11-20T10:00:00Z"),
      dateLabel: "Nov 20 – Dec 10, 2026",
      durationLabel: "3 weeks",
      registrationDeadline: new Date("2026-11-18T23:59:59Z"),
      price: "Free",
      registrationFee: "Free",
      capacity: 80,
      seats: 80,
      registeredCount: 0,
      coverImage: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&auto=format&fit=crop&q=80",
      status: "PENDING_REVIEW",
      organizer: organizerUser._id,
      organizerName: "DevSphere Foundation",
      isFeatured: false,
      registrationsOpen: true,
      tags: ["Cryptography", "ZK", "Security", "Bootcamp"],
    },
  ];

  const createdEvents = await Event.insertMany(eventsData);
  logger.info(`Seeded ${createdEvents.length} full-spectrum events (${createdEvents.filter(e => e.status === "APPROVED").length} Approved & Published, 1 Pending Review).`);

  const primaryEvent = createdEvents[0]; // Quantum Hack

  // 5. Seed Registrations for Students
  await Registration.create({
    user: student._id,
    event: primaryEvent._id,
    status: "REGISTERED",
    ticketCode: "IGN-HAC-8812",
    seatNumber: "HAC-B04",
    userName: student.name,
    userEmail: student.email,
    college: student.college,
    phone: "+91 91234 56789",
    eventTitle: primaryEvent.title,
    eventDate: primaryEvent.dateLabel,
    eventLocation: primaryEvent.location,
    registeredAt: new Date(),
  });

  await Registration.create({
    user: student2._id,
    event: primaryEvent._id,
    status: "REGISTERED",
    ticketCode: "IGN-HAC-9021",
    seatNumber: "HAC-B05",
    userName: student2.name,
    userEmail: student2.email,
    college: student2.college,
    phone: "+91 98888 12345",
    eventTitle: primaryEvent.title,
    eventDate: primaryEvent.dateLabel,
    eventLocation: primaryEvent.location,
    registeredAt: new Date(),
  });

  // 6. Seed Announcements & Banners
  await Announcement.create({
    title: "Global AI Hackathon Registrations Open!",
    content: "Over ₹25,00,000 in bounties announced for open-source AI models. Register before seats fill.",
    message: "Over ₹25,00,000 in bounties announced for open-source AI models. Register before seats fill.",
    type: "info",
    active: true,
    createdBy: adminUser._id,
  });

  await Banner.create({
    title: "Build the Future at Ignite 2026",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&auto=format&fit=crop&q=80",
    description: "Discover premier hackathons, tech conferences, and university summits across India.",
    ctaText: "Explore Events",
    ctaLink: "/events",
    active: true,
    displayOrder: 1,
    createdBy: adminUser._id,
  });

  logger.info("==========================================");
  logger.info("✅ Ignite Enginow Database Seed Complete!");
  logger.info("==========================================");

  if (standalone) {
    await closeDB();
  }
};

const isMain = process.argv[1]?.replace(/\\/g, "/").endsWith("scripts/seed.js");
if (isMain) {
  seedData(true).catch((err) => {
    logger.error("Seed failed:", err);
    process.exit(1);
  });
}
